debug: false

server:
  port: 8001

logging:
  level:
    root: INFO
    com.ezappx: DEBUG

spring:
  main:
    banner-mode: "off"

  application:
    name: designer

  datasource:
    url: jdbc:postgresql://localhost:5432/ezappxdev
    username: guest
    password: guest
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  redis:
    host: localhost
    port: 6379
    password: guest
    database: 0

  servlet:
    multipart:
      enabled: true
      max-file-size: "10MB"

